<?php
 $title = 'THÊM BẢNG TIN';
 $this->headTitle($title);
 ?>
 <h1>
 	<?php echo $this->escapeHtml($title); ?>
 </h1>
 <?php
 $bangTin=$form->get('bang-tin');
 $danhMuc=$bangTin->get('idDanhMuc');
 $khuVuc=$bangTin->get('idKhuVuc');
 $mucDoVip=$bangTin->get('idMucDoVip');
 $loaiTin=$bangTin->get('idLoaiTin');
 $hinhAnh=$bangTin->get('hinhAnh');
 echo $this->formHidden($bangTin->get('idTin'));
?>

<div class="form-group"> 	
 		<?php $tieuDe=$bangTin->get('tieuDe');?>
 		<?php $tieuDe->setAttribute('class','form-control');?>
 		<label><?php echo $tieuDe->getLabel(); ?></label>
 		<?php echo $this->formElement($tieuDe);?> 
</div>
<div class="form-group"> 	
 		<?php $noiDung=$bangTin->get('noiDung');?>
 		<?php $noiDung->setAttribute('class','form-control');?>
 		<label><?php echo $noiDung->getLabel(); ?></label>
 		<?php echo $this->formElement($noiDung);?> 
</div>

<div class="form-group"> 	
 		<?php $ngayDang=$bangTin->get('ngayDang');?>
 		<?php $ngayDang->setAttribute('class','form-control');?>
 		<label><?php echo $ngayDang->getLabel(); ?></label>
 		<?php echo $this->formElement($ngayDang);?> 
</div>
<div class="form-group"> 	
 		<?php $ngayKetThuc=$bangTin->get('ngayKetThuc');?>
 		<?php $ngayKetThuc->setAttribute('class','form-control');?>
 		<label><?php echo $ngayKetThuc->getLabel(); ?></label>
 		<?php echo $this->formElement($ngayKetThuc);?> 
</div>

<?php 
	$submit=$form->get('submit'); 
	$submit->setValue('Thêm Bảng Tin');
	echo $this->formSubmit($submit);
	echo $this->form()->closeTag();
?>