<?php
 $title = 'THÊM BẢNG TIN';
 $this->headTitle($title);
 ?>
 <h1>
 	<?php echo $this->escapeHtml($title); ?>
 </h1>

<?php
 $form->setAttribute('action', $this->url('rao_vat/crud', array('action' => 'add')));
 $form->setAttribute('role','form');
 $form->prepare();
 echo $this->form()->openTag($form);
?>


 <?php
 $bangTin=$form->get('bang-tin');
 $danhMuc=$bangTin->get('idDanhMuc');
 $khuVuc=$bangTin->get('idKhuVuc');
 $mucDoVip=$bangTin->get('idMucDoVip');
 $loaiTin=$bangTin->get('idLoaiTin');
 $hinhAnh=$bangTin->get('hinhAnh');
 echo $this->formHidden($bangTin->get('idTin'));
?>

<div class="form-group"> 	
 		<?php $tieuDe=$bangTin->get('tieuDe');?>
 		<?php $tieuDe->setAttribute('class','form-control');?>
 		<label><?php echo $tieuDe->getLabel(); ?></label>
 		<?php echo $this->formElement($tieuDe);?> 
</div>
<div class="form-group"> 	
 		<?php $noiDung=$bangTin->get('noiDung');?>
 		<?php $noiDung->setAttribute('class','form-control');?>
 		<label><?php echo $noiDung->getLabel(); ?></label>
 		<?php echo $this->formElement($noiDung);?> 
</div>

<div class="form-group"> 	
 		<?php $ngayDang=$bangTin->get('ngayDang');?>
 		<?php $ngayDang->setAttribute('class','form-control');?>
 		<label><?php echo $ngayDang->getLabel(); ?></label>
 		<?php echo $this->formElement($ngayDang);?> 
</div>
<div class="form-group"> 	
 		<?php $ngayKetThuc=$bangTin->get('ngayKetThuc');?>
 		<?php $ngayKetThuc->setAttribute('class','form-control');?>
 		<label><?php echo $ngayKetThuc->getLabel(); ?></label>
 		<?php echo $this->formElement($ngayKetThuc);?> 
</div>
<div class="form-group"> 	
 		<?php $hinhAnh=$bangTin->get('hinhAnh');?>
 		<?php $hinhAnh->setAttribute('class','form-control');?> 		
 		<?php echo $this->formElement($hinhAnh);?> 
</div>

<div class="form-group"> 	
 		<?php $danhMuc=$bangTin->get('idDanhMuc');?>
 		<?php $danhMuc->setLabel('Thuộc danh mục'); ?>
 		<?php $danhMuc->setAttribute('class','form-control');?>
 		<label><?php echo $danhMuc->getLabel(); ?></label>
 		<?php //$danhMuc->setValueOptions($this->makeArrayCollection(NULL));?> 	 	
 		<?php echo $this->formElement($danhMuc);?> 
</div>


<div class="form-group"> 	
 		<?php $khuVuc=$bangTin->get('idKhuVuc');?>
 		<?php $khuVuc->setLabel('Khu vực'); ?>
 		<?php $khuVuc->setAttribute('class','form-control');?>
 		<label><?php echo $khuVuc->getLabel(); ?></label>
 		<?php //$khuVuc->setValueOptions($this->makeArrayCollection(NULL));?> 	 	
 		<?php echo $this->formElement($khuVuc);?> 
</div>


<div class="form-group"> 	
 		<?php $mucDoVip=$bangTin->get('idMucDoVip');?>
 		<?php $mucDoVip->setLabel('Mức độ vip'); ?>
 		<?php $mucDoVip->setAttribute('class','form-control');?>
 		<label><?php echo $mucDoVip->getLabel(); ?></label>
 		<?php //$mucDoVip->setValueOptions($this->makeArrayCollection(NULL));?> 	 	
 		<?php echo $this->formElement($mucDoVip);?> 
</div>

<div class="form-group"> 	
 		<?php $loaiTin=$bangTin->get('idLoaiTin');?>
 		<?php $loaiTin->setLabel('Loại tin'); ?>
 		<?php $loaiTin->setAttribute('class','form-control');?>
 		<label><?php echo $loaiTin->getLabel(); ?></label>
 		<?php //$loaiTin->setValueOptions($this->makeArrayCollection(NULL));?> 	 	
 		<?php echo $this->formElement($loaiTin);?> 
</div>

<?php 
	$submit=$form->get('submit'); 
	$submit->setValue('Thêm Bảng Tin');
	echo $this->formSubmit($submit);
	echo $this->form()->closeTag();
?>