<?php

 $title = 'Xóa';
 $this->headTitle($title);
 ?>
 <h1><?php echo $this->escapeHtml($title); ?></h1>

 <p>Bạn muốn xóa bản tin 
     '<?php echo $this->escapeHtml($bangTin->getTieuDe()); ?>'?
 </p>
 <?php
 $url = $this->url('rao_vat/crud', array(
     'action' => 'delete',
     'id'     => $this->id,
 ));
 ?>
 <form action="<?php echo $url; ?>" method="post">
 <div>
     <input type="hidden" name="id" value="<?php echo (int) $bangTin->getId(); ?>" />
     <input type="submit" name="del" value="Yes" />
     <input type="submit" name="del" value="No" />
 </div>
 </form>