<?php
 use Zend\Form\Element;

 $title = 'SỬA BẢNG TIN';
 $this->headTitle($title);
 ?>
 <h1>
 	<?php echo $this->escapeHtml($title); ?>
 </h1>
<a href="<?php echo $this->url('rao_vat'); ?>">Quay lại</a>
<?php
 $form->setAttribute('action', $this->url('rao_vat/crud',array('action' => 'edit','id'=> $this->id)));
 $form->setAttribute('role','form');
 $form->prepare();
 echo $this->form()->openTag($form);
?>

<?php
 $bangTin=$form->get('bang-tin');
 echo $this->formHidden($bangTin->get('idTin'));
?>
<div class="form-group"> 	
	<?php $tieuDe=$bangTin->get('tieuDe'); ?>
	<?php $tieuDe->setAttribute('class','form-control'); ?>
	<label><?php echo $tieuDe->getLabel(); ?></label>
	<?php echo $this->formElement($tieuDe); ?> 
</div>
<div class="form-group"> 	
	<?php $noiDung=$bangTin->get('noiDung'); ?>
	<?php $noiDung->setAttribute('class','form-control');?>
	<label><?php echo $noiDung->getLabel(); ?></label>
	<?php echo $this->formElement($noiDung); ?> 
</div>

<div class="form-group"> 	
	<?php $ngayDang=$bangTin->get('ngayDang'); ?>
	<?php $ngayDang->setAttribute('class','form-control'); ?>
	<label><?php echo $ngayDang->getLabel(); ?></label>
	<?php echo $this->formElement($ngayDang); ?> 
</div>
<div class="form-group"> 	
	<?php $ngayKetThuc=$bangTin->get('ngayKetThuc'); ?>
	<?php $ngayKetThuc->setAttribute('class','form-control'); ?>
	<label><?php echo $ngayKetThuc->getLabel(); ?></label>
	<?php echo $this->formElement($ngayKetThuc); ?> 
</div>
<div class="form-group"> 
	<?php $danhMuc=$bangTin->get('idDanhMuc');?>
	<?php $danhMuc->setAttribute('class','form-control');?>
	<label><?php echo $danhMuc->getLabel(); ?></label>
	<?php $danhMuc->setValueOptions($this->MakeArrayOptionTaxonomy($danhMucs));?> 	 	
	<?php echo $this->formElement($danhMuc);?> 
</div>
<div class="form-group"> 	
	<?php $khuVuc=$bangTin->get('idKhuVuc'); ?>
	<?php $khuVuc->setLabel('Khu vực'); ?>
	<?php $khuVuc->setAttribute('class','form-control'); ?>
	<label><?php echo $khuVuc->getLabel(); ?></label>
	<?php $khuVuc->setValueOptions($this->MakeArrayOptionTaxonomy($khuVucs)); ?> 	 	
	<?php echo $this->formElement($khuVuc); ?> 
</div>


<div class="form-group"> 	
	<?php $mucDoVip=$bangTin->get('idMucDoVip'); ?>
	<?php $mucDoVip->setLabel('Mức độ vip'); ?>
	<?php $mucDoVip->setAttribute('class','form-control'); ?>
	<label><?php echo $mucDoVip->getLabel(); ?></label>
	<?php $mucDoVip->setValueOptions($this->makeArrayOptionMucDoVip($mucDoVips)); ?> 	 	
	<?php echo $this->formElement($mucDoVip); ?> 
</div>

<div class="form-group"> 	
	<?php $loaiTin=$bangTin->get('idLoaiTin'); ?>
	<?php $loaiTin->setLabel('Loại tin'); ?>
	<?php $loaiTin->setAttribute('class','form-control'); ?>
	<label><?php echo $loaiTin->getLabel(); ?></label>
	<?php $loaiTin->setValueOptions($this->makeArrayOptionLoaiTin($loaiTins)); ?> 	 	
	<?php echo $this->formElement($loaiTin); ?> 
</div>
<table>
	
<?php 
	foreach($hinhAnhs as $hinhAnh)
	{?>
		<tr>
			<td>
				<?php //die(var_dump($hinhAnh->getViTri())); ?>
				<?php echo '<img src="../../img/'.$hinhAnh->getViTri().'" width="50px"/>'; ?>
			</td>
		<tr>
		</tr>
			<td>
				<a href="<?php echo $this->url('rao_vat/crud',
             array('action'=>'deleteImage','id'=>$hinhAnh->getIdHinhAnh()));?> ">Xóa</a>
			</td>
		</tr>
	<?php
		
	}  
?>
</table>
<div class="form-group"> 	
	<?php $hinhAnh=$bangTin->get('hinhAnhs')->get('hinhAnhs');?>
	<?php $hinhAnh->setAttribute('class','form-control');?> 		
	<?php echo $this->formElement($hinhAnh);?> 
</div>
<?php 
	$submit=$form->get('submit'); 
	$submit->setValue('Sửa Bảng Tin');
	echo $this->formSubmit($submit);
	echo $this->form()->closeTag();
?>
