<?php //die(var_dump($bangTins[1]->getHinhAnhs()[0]->getViTri())); ?>
<table border="0" align="center" width="100%" height="200px" style="border-spacing:0px;">	
<?php $i=0;
	foreach($bangTins as $bangTin)
	{?>
		<?php $i+=1;		
		if($i==1||$i==2)
		{
			if($i==1)
			{
				echo '<tr>';
			}
		?>
		<?php 
			if($i==1&&count($bangTins)>1)
			{
				echo '<td width="500px;" style="border-right:10px solid #E6F0A4;">';
			}
			else
				echo '<td width="500px;">';
		?>			
					<table align="center" width="100%" height="100%" style="background-color:white;">	

						<tr>
							<td >								
									<b>
										<?php echo $this->escapeHtml($bangTin->getTieuDe());?>
									</b>
								
							</td>
						</tr>
						<tr>
							<td >
								Giá:<b>
										<a style="color:#eea236;" href="<?php echo $this->url('rao_vat/crud',array('action' => 'xemTinTheoGia', 'id' => $bangTin->getGia())); ?>">
											<?php echo $this->escapeHtml($bangTin->getGia());?>
										</a>
									</b> VNĐ. 
								<br>
								Ngày đăng: <a href="<?php echo $this->url('rao_vat/crud',array('action' => 'xemTinTheoNgay', 'id' => $bangTin->getIdTin())); ?>">
									<b style="color:blue;">
										<?php echo $this->escapeHtml(date_format($bangTin->getNgayDang(),'d/m/Y'));?>
									</b>
								</a>
							</td>
						</tr>
						<tr>
							<td>
								<table width="100%" height="100%" align="center" style='background-color:#C0C0C0'>
									<tr>
										<td width="84%" height="100%" style='text-align:center'>
										<?php
											$yMD=$bangTin->getNgayTao()->format('Y/m/d');
											foreach ($bangTin->getHinhAnhs() as $hinhAnh) {
												if($hinhAnh->getMain()==1)
												{
													echo '<img src="'.$this->basePath().'/img/'.$yMD.'/'.$hinhAnh->getViTri().'" width="300px" height="400px" align="center"/>';
												}
												
											}
										?>
										</td>
										<?php
										if(count($bangTin->getHinhAnhs())>1)
										{?>
											<td width="75px">
												<?php
													$co=0;
													foreach ($bangTin->getHinhAnhs() as $hinhAnh) {													
														$co++;
														if($co<=10)
														{
															echo '&nbsp;&nbsp;<img src="'.$this->basePath().'/img/'.$yMD.'/'.$hinhAnh->getViTri().'" width="60px" height=80px"/>';
															echo '<br>';
														}
														if($co==5)
														{
															echo '</td><td width="75px">';
														}														
													}											
												?>
											</td>
											
										<?php
										}
										?>
									</tr>
								</table>
							</td>
						</tr>						
						<tr>						
							<td>
								<a href="<?php echo $this->url('rao_vat/crud',array('action' => 'xemTheoLoaiTin', 'id' => $bangTin->getIdLoaiTin()->getIdLoaiTin())); ?>">
									<?php
										echo '<b style="color:#357ebd;">'.$bangTin->getIdLoaiTin()->getTenLoaiTin().':</b><br>';
									?>
								</a>
								<?php 
									echo $this->escapeHtml($bangTin->getNoiDung());
								?>								
							</td>
						</tr>
						<tr>						
							<td height ="30px;" style="color:#C0C0C0;">Danh muc:
								<a href="<?php echo $this->url('rao_vat/crud',array('action' => 'xemTinTheoDanhMuc', 'id' => $bangTin->getIdDanhMuc()->getTermTaxonomyId())); ?>" style="color:#C0C0C0;">
									<?php echo $this->escapeHtml($bangTin->getIdDanhMuc()->getTermId()->getName());?>
								</a>
							</td>
						</tr>
						<tr>							
							<td height ="30px;" style="color:#C0C0C0;">Khu vực:
								<a href="<?php echo $this->url('rao_vat/crud',array('action' => 'xemTinTheoKhuVuc', 'id' => $bangTin->getIdKhuVuc()->getTermTaxonomyId())); ?>" style="color:#C0C0C0;">
									<?php echo $this->escapeHtml($bangTin->getIdKhuVuc()->getTermId()->getName());?>
								</a>
							</td>
						</tr>
					</table>
				</td>
		<?php
			if($i==2)
			{
				echo '</tr><tr>
						<td height="10px"></td>
						<td></td>
					  </tr>';
				$i=0;
			}		
		}				
	}
	if($i==1)  
	{
		echo "</tr>";
	}
?>
</table>
