<?php //die(var_dump($bangTins[1]->getHinhAnhs()[0]->getViTri())); ?>
<table border="0" align="center" width="100%" height="300px" style="border-spacing:0px; font-size:20px;">	
<?php $i=0;
	foreach($bangTins as $bangTin)
	{?>
		<?php $i+=1;		
		if($i==1||$i==2)
		{
			if($i==1)
			{
				echo '<tr>';
			}
		?>	
				<td width="500px;">
					<table align="center" width="100%" height="100%" style="border:thin solid blue; background:white">	

						<tr>
							<td colspan="2">
								<?php echo 'Tiêu đề: <b>'.$this->escapeHtml($bangTin->getTieuDe());?></b>
								
							</td>
						</tr>
						<tr>
							<td rowspan="4" width="150px" height="250px">
								<table align="center" width="100%" height="100%" border="1px" style="border-spacing:0px; border-padding:0px; border-left:none; border-top:none; border-right:none; border-bottom:none; margin-left:-4px; margin-bottom:-4px; border-color:blue; ">
									<tr>
										<td>
										<?php
											$yMD=$bangTin->getNgayTao()->format('Y/m/d');
											//die(var_dump($yMD));
											foreach ($bangTin->getHinhAnhs() as $hinhAnh) {
												if($hinhAnh->getMain()==1)
												{
													echo '<img src="'.$this->basePath().'/img/'.$yMD.'/'.$hinhAnh->getViTri().'" width="150px" height="200px"/>';
												}
												
											}
										?>
										</td>	
									</tr>
									<tr>
										<td height="50px" style="border-top:none; background-color: #C0C0C0;">
										<?php
											if(count($bangTin->getHinhAnhs())>1)
											{
												$co=0;
												foreach ($bangTin->getHinhAnhs() as $hinhAnh) {												
													if($hinhAnh->getMain()!=1)
													{
														if(count($bangTin->getHinhAnhs())<=4)
														{
															$co++;
															if($co<=3)
															{
																echo '&nbsp;&nbsp;<img src="'.$this->basePath().'/img/'.$yMD.'/'.$hinhAnh->getViTri().'" width="40px" height="50px"/>';
															}	
														}	
														else										
														{
															$co++;
															if($co<=2)
															{
																echo '&nbsp;&nbsp;<img src="'.$this->basePath().'/img/'.$yMD.'/'.$hinhAnh->getViTri().'" width="40px" height="50px"/>';
															}
															if($co==3)
															{
																echo '&nbsp;&nbsp;<a href="#" style="font-size:14px; color:black"><b>Next</b></a>';
															}
														}
													}
													
												}
											}
											else
											{
												echo '&nbsp;&nbsp;<img src="'.$this->basePath().'/img/DefaultImage.jpg'.'" width="40px" height="50px"/>';
											}

										?>
										</td>	
									</tr>
								</table>
							</td>
							<td height="50px;">
							Giá:<b style="color:red"><?php echo $this->escapeHtml($bangTin->getGia());?></b> VNĐ <br> Ngày đăng: <b style="color:blue;"><?php echo $this->escapeHtml(date_format($bangTin->getNgayDang(),'d/m/Y'));?></b>
							</td>
						</tr>
						<tr>						
							<td>
								<?php
									echo '<b style="color:blue;">'.$bangTin->getIdLoaiTin()->getTenLoaiTin().':</b><br>';
								?>
								<?php echo $this->escapeHtml($bangTin->getNoiDung());?>
							</td>
						</tr>
						<tr>						
							<td height ="30px;" style="color:#C0C0C0;">Danh muc:
								<?php echo $this->escapeHtml($bangTin->getIdDanhMuc()->getTermId()->getName());?>
							</td>
						</tr>
						<tr>							
							<td height ="30px;" style="color:#C0C0C0;">Khu vực:
								<?php echo $this->escapeHtml($bangTin->getIdKhuVuc()->getTermId()->getName());?>
							</td>
						</tr>
					</table>
				</td>
		<?php
			if($i==2)
			{
				echo '</tr>';
				$i=0;
			}		
		}				
	}  
?>
</table>
