<?php //die(var_dump($bangTins[1]->getHinhAnhs()[0]->getViTri())); ?>
<table border="0" align="center" width="100%" height="300px">	
<?php $i=0;
	foreach($bangTins as $bangTin)
	{?>
		<?php $i+=1;		
		if($i==1||$i==2)
		{
			if($i==1)
			{
				echo '<tr>';
			}
		?>	
				<td>
					<table align="center" width="100%" height="100%" style="border:thin solid blue; background:white">	

						<tr>
							<td colspan="2">
								<?php echo $this->escapeHtml($bangTin->getTieuDe());?>
							<br>
								<?php echo "Ngày đăng: ".$this->escapeHtml(date_format($bangTin->getNgayDang(),'d/m/Y'));?>
							</td>
						</tr>
						<tr>
							<td rowspan="4" width="150px" height="250px">
								<table align="center" width="100%" height="100%" border="1px" style="border-spacing:0px; border-padding:0px; border-color:blue; ">
									<tr>
										<td>
										<?php
											$yMD=$bangTin->getNgayTao()->format('Y/m/d');
											//die(var_dump($yMD));
											foreach ($bangTin->getHinhAnhs() as $hinhAnh) {
												if($hinhAnh->getMain()==1)
												{
													echo '<img src="'.$this->basePath().'/img/'.$yMD.'/'.$hinhAnh->getViTri().'" width="150px" height="200px"/>';
												}
												
											}
										?>
										</td>	
									</tr>
									<tr>
										<td height="50px">Ảnh nhỏ</td>	
									</tr>
								</table>
							</td>
							<td>Giá:
								<?php echo $this->escapeHtml($bangTin->getGia());?> vnđ
							</td>
						</tr>
						<tr>						
							<td>
								<?php echo $this->escapeHtml($bangTin->getNoiDung());?>
							</td>
						</tr>
						<tr>						
							<td>Danh muc:
								<?php echo $this->escapeHtml($bangTin->getIdDanhMuc()->getTermId()->getName());?>
							</td>
						</tr>
						<tr>							
							<td>Khu vực:
								<?php echo $this->escapeHtml($bangTin->getIdKhuVuc()->getTermId()->getName());?>
							</td>
						</tr>
					</table>
				</td>
		<?php
			if($i==2)
			{
				echo '</tr>';
				$i=0;
			}		
		}				
	}  
?>
</table>
