<table border="0" align="center" width="100%" height="300px">	
<?php $i=0;
	foreach($bangTins as $bangTin)
	{?>
		<?php $i+=1;		
		if($i==1)
		{?>	
			<tr>
				<td>
					<table align="center" width="100%" height="100%" style="border:thin solid blue; background:white">	

						<tr>
							<td colspan="2">
								<?php echo $this->escapeHtml($bangTin->getTieuDe());?>
							<br>
								<?php echo "Ngày đăng: ".$this->escapeHtml(date_format($bangTin->getNgayDang(),'d/m/Y'));?>
							</td>
						</tr>
						<tr>
							<td rowspan="4" width="150px" height="200px">
								<table align="center" width="100%" height="100%" border="1px" style="border-spacing:0px; border-padding:0px; border-color:blue; ">
									<tr>
										<td>Ảnh đại diện</td>	
									</tr>
									<tr>
										<td height="50px">Ảnh nhỏ</td>	
									</tr>
								</table>
							</td>
							<td>Giá:
								<?php echo $this->escapeHtml($bangTin->getGia());?> vnđ
							</td>
						</tr>
						<tr>						
							<td>
								<?php echo $this->escapeHtml($bangTin->getNoiDung());?>
							</td>
						</tr>
						<tr>						
							<td>Danh muc:
								<?php echo $this->escapeHtml($bangTin->getIdDanhMuc()->getTermId()->getName());?>
							</td>
						</tr>
						<tr>							
							<td>Khu vực:
								<?php echo $this->escapeHtml($bangTin->getIdKhuVuc()->getTermId()->getName());?>
							</td>
						</tr>
					</table>
				</td>
		<?php		
		}
		if($i==2)
		{?>
				<td>
					<table align="center" width="100%" height="100%" style="border:thin solid blue; background:white">	

						<tr>
							<td colspan="2">
								<?php echo $this->escapeHtml($bangTin->getTieuDe());?>
							<br>
								<?php echo "Ngày đăng: ".$this->escapeHtml(date_format($bangTin->getNgayDang(),'d/m/Y'));?>
							</td>
						</tr>
						<tr>
							<td rowspan="4" width="150px" height="200px">
								<table align="center" width="100%" height="100%" border="1px" style="border-spacing:0px; border-padding:0px; border-color:blue; ">
									<tr>
										<td>Ảnh đại diện</td>	
									</tr>
									<tr>
										<td height="50px">Ảnh nhỏ</td>	
									</tr>
								</table>
							</td>
							<td>Giá:
								<?php echo $this->escapeHtml($bangTin->getGia());?> vnđ
							</td>
						</tr>
						<tr>						
							<td>
								<?php echo $this->escapeHtml($bangTin->getNoiDung());?>
							</td>
						</tr>
						<tr>						
							<td>Danh muc:
								<?php echo $this->escapeHtml($bangTin->getIdDanhMuc()->getTermId()->getName());?>
							</td>
						</tr>
						<tr>							
							<td>Khu vực:
								<?php echo $this->escapeHtml($bangTin->getIdKhuVuc()->getTermId()->getName());?>
							</td>
						</tr>
					</table>
				</td>
			</tr>
		 <?php $i=0;	
		}				
	}  
?>
</table>