<?php $this->layout('layout/giaodien');?>

<?php
$form = $this->loginForm;
$form->prepare();
$form->setAttribute('action', $this->url('zfcuser/login'));
$form->setAttribute('method', 'post');
?>

<?php echo $this->form()->openTag($form) ?>
    <br><br>
    <table align="center">
      <tr>
          <td>
            <span class="label label-warning"><label for="email" style="width:800px; font-size:14px;">
                   Vui lòng <a href="" class="alert-link">ĐĂNG NHẬP</a> bằng tài khoản của bạn. Nếu bạn chưa có tài khoản vui lòng <a href="<?php echo $this->url('zfcuser/register', array('action'=>'register'));?>" title="Đăng ký để đăng tin Vip">ĐĂNG KÝ tại đây</a> 
            </label></span>
            </td>
        </tr>
    </table>
    
     <table hidden="true">
      <tr>
          <td style="text-align:center; padding-bottom:10px;">            
                  <span class="label label-primary" style="padding-left:150px; padding-right:150px; text-align:center; font-size:16px;">ĐĂNG NHẬP</span>
          </td>
        </tr>
        <tr>
            <td>
                <?php echo $this->formElementErrors($form->get('identity')) ?>                
            </td>
        </tr>

         <tr>
            <td>
                <span class="label label-primary"><label for="email" style="width:150px;">
                    <?php echo $this->formLabel($form->get('identity')) ?>
                </label></span>
            </td>
        </tr>

         <tr>
            <td>
                <?php $form->get('identity')->setAttribute('class','form-control');?> 
                <?php echo $this->formInput($form->get('identity')) ?>
            </td>
        </tr>

         <tr>
            <td>
                <span class="label label-primary"><label for="email" style="width:150px;">
                    <?php echo $this->formLabel($form->get('credential')) ?>
                </label></span>
            </td>
        </tr>

        <tr>
            <td>
                <?php $form->get('credential')->setAttribute('class','form-control');?> 
                <?php echo $this->formInput($form->get('credential')) ?>
            </td>
        </tr>

         <tr>
            <td>
                <?php if ($this->redirect): ?>
                    <input type="hidden" name="redirect" value="<?php echo $this->escapeHtml($this->redirect) ?>" />
                <?php endif ?>
                <?php $form->get('submit')->setAttribute('class','btn btn-primary');?>
                <?php echo $this->formButton($form->get('submit')) ?>
                &nbsp;
                <a href="<?php echo $this->url('zfcuser/register', array('action'=>'register'));?>" title="Đăng ký để đăng tin Vip">
                    <button type="button" class="btn btn-warning">
                        Đăng ký
                    </button>
                </a>
            </td>
        </tr>

         <tr>
            <td>
            </td>
        </tr>

    </table>

<?php echo $this->form()->closeTag() ?>

<?php if ($this->enableRegistration) : ?>
    
<?php endif; ?>
