<?php $this->layout('layout/giaodien');?>
<?php
if (!$this->enableRegistration) {
    print "Registration is disabled";
    return;
}
$form = $this->registerForm;
$form->prepare();
$form->setAttribute('action', $this->url('zfcuser/register'));
$form->setAttribute('method', 'post');
?>
<?php echo $this->form()->openTag($form) ?>
    <table align="center" width="100%">
      <tr>
          <td style="text-align:center; padding-bottom:10px;">            
                  <span class="label label-primary" style="padding-left:390px; padding-right:390px; text-align:center; font-size:16px;">ĐĂNG KÝ THÀNH VIÊN</span>
          </td>
        </tr>
    </table>
  
    <dl class="zend_form">      
    <?php foreach ($form as $element): ?>
        <?php if (!$element instanceof Zend\Form\Element\Button): ?>
            <dt>
              <span class="label label-primary"><label for="email" style="width:150px;"><?php echo $this->formLabel($element) ?></label></span>
            </dt>
        <?php endif ?>
        <?php if ($element instanceof Zend\Form\Element\Button): ?> 
            <dt>&nbsp;
            </dt>       
            <dd>
                <?php $element->setAttribute('class','btn btn-primary');?>
                <?php echo $this->formButton($element); ?>&nbsp;&nbsp;&nbsp;&nbsp;               
                <a href="<?php echo $this->url('zfcuser/register',array('action'=>'logout'));?>">
                <button type="button" class="btn btn-warning">
                  Nhập lại
              </button>
            </a>
            </dd>
        <?php elseif ($element instanceof Zend\Form\Element\Captcha): ?>
            <dd>   
                 <?php $element->setAttribute('class','form-control');?> 
                 <?php echo $this->formCaptcha($element); ?>
                 <?php echo $this->formElementErrors($element); ?>

            </dd>
        <?php else: ?>
            <dd>
              <?php $element->setAttribute('class','form-control');?>
              <?php echo $this->formInput($element); ?>
              <?php echo  $this->formElementErrors($element); ?>
            </dd>
        <?php endif ?>
    <?php endforeach ?>
    </dl>
    <?php if ($this->redirect): ?>
        <input type="hidden" name="redirect" value="<?php echo $this->escapeHtml($this->redirect) ?>" />
    <?php endif ?>
<?php echo $this->form()->closeTag() ?>
       
