<!DOCTYPE HTML>
<!-- Website Template by freewebsitetemplates.com -->
<html>
<script type="text/javascript">
	function tb()
	{
		alert("Đang xây dựng");
	}	
</script>
<head>
	<meta charset="UTF-8">
	<title>Rao vặt</title>
	<link rel="stylesheet" href="<?php echo $this->basePath();?>/css/style-template.css" type="text/css">
	<!-- Le styles -->
        <?php echo $this->headLink(array('rel' => 'shortcut icon', 'type' => 'image/vnd.microsoft.icon', 'href' => $this->basePath() . '/img/favicon.ico'))
                        ->prependStylesheet($this->basePath() . '/css/style.css')
                        ->prependStylesheet($this->basePath() . '/css/bootstrap-theme.min.css')
                        ->prependStylesheet($this->basePath() . '/css/bootstrap.min.css') ?>

        <!-- Scripts -->
        <?php echo $this->headScript()
            ->prependFile($this->basePath() . '/js/bootstrap.min.js')
            ->prependFile($this->basePath() . '/js/jquery.min.js')
            ->prependFile($this->basePath() . '/js/respond.min.js', 'text/javascript', array('conditional' => 'lt IE 9',))
            ->prependFile($this->basePath() . '/js/html5shiv.js',   'text/javascript', array('conditional' => 'lt IE 9',))
        ; ?>

</head>
<body style="margin-top:-60px; background-color:#E6F0A4;">
	<div id="header">
	<?php
		$url = $this->url('rao_vat/crud', array(
		     'action' => 'login'
		 ));
	?>	 
	<form method="post" action="<?php echo $url; ?>">	
		<table border="0" align="right" style="margin-top:50px;margin-right:0px">
		<?php
		if ($this->zfcUserIdentity()) 
		{?>
			<tr>
				
				<td>
					<button type="submit" class="btn btn-primary" disabled="disabled"><?php echo "Chào: ".$this->zfcUserIdentity()->getEmail();?></button>								
				</td>
				<td>	
					<a href="<?php echo $this->url('rao_vat/crud',array('action'=>'logout'));?>">
         				<button type="button" class="btn btn-primary">
        					Thoát
     					</button>
     				</a>
				</td>
			</tr>
			<tr>
				<td colspan="2">
					<a href="<?php echo $this->url('rao_vat/crud', array('action'=>'add')); ?>" style="text-decoration: none;" title="Đăng tin miễn phí. Đăng nhập để đăng tin Vip">
						<button type="button" class="btn btn-warning"  name="btDangTin" style="width:100%;">Đăng tin miễn phí</button>
					</a>
				</td>
			</tr>
		<?php
		}
		else
		{?>
			<tr>
				<td>
					<button type="submit" class="btn btn-primary" style="width:100%;">
						Đăng nhập
					</button>
					</br>&nbsp;
				</td>
				<td style="text-align:right">					
				  <div class="form-group">
				    <input type="email" class="form-control" id="exampleInputEmail1" name="identity" placeholder="Enter email">
				  </div>
				</td>
				<td>
					<div class="form-group">
				    <input type="password" class="form-control" id="exampleInputPassword1" name="credential" placeholder="Password">
				  </div>
					
				</td>
			</tr>
			<tr>
				<td>
					<a href="<?php echo $this->url('rao_vat/crud', array('action'=>'add'));?>" style="text-decoration: none;" title="Đăng tin miễn phí. Đăng nhập để đăng tin Vip">
						<button type="button" class="btn btn-warning"  name="btDangTin" style="width:100%;">Đăng tin miễn phí</button>
					</a>
					
				</td>
				<td align="center">
					<a href="<?php echo $this->url('zfcuser/register', array('action'=>'register'));?>" title="Đăng ký để đăng tin Vip">
						<button type="button" class="btn btn-primary" style="width:100%;">
							Đăng ký
						</button>
					</a>
				</td>
				<td align="center">
					<a href="#" onclick="return tb();">
						<button type="button" class="btn btn-primary" style="width:100%;">
							Quên mật khẩu
						</button>
					</a>
				</td>
			</tr>
		<?php
		}
		?>
			
		</table>
	</form>

		<div class="section">
			<div class="logo">
				<a href="<?php echo $this->url('rao_vat'); ?>">
				</a>
			</div>				
		</div>
		
	</div>
	<div id="body">
		<?php echo $this->content; ?>
	</div>
	<div id="footer">
		<div>
			<div class="connect">
				<a href="http://freewebsitetemplates.com/go/twitter/" id="twitter">twitter</a>
				<a href="http://freewebsitetemplates.com/go/facebook/" id="facebook">facebook</a>
				<a href="http://freewebsitetemplates.com/go/googleplus/" id="googleplus">googleplus</a>
				<a href="http://pinterest.com/fwtemplates/" id="pinterest">pinterest</a>
			</div>
			<p>
				&copy; Copyright 2014 | S3U Group.
			</p>
		</div>
	</div>
</body>
</html>