<!DOCTYPE HTML>
<!-- Website Template by freewebsitetemplates.com -->
<html>
<script type="text/javascript">
	function tb()
	{
		alert("Đang xây dựng");
	}	
</script>
<head>
	<meta charset="UTF-8">
	<title>Rao vặt</title>
	<link rel="stylesheet" href="<?php echo $this->basePath();?>/css/style-template.css" type="text/css">
	<!-- Le styles -->
        <?php echo $this->headLink(array('rel' => 'shortcut icon', 'type' => 'image/vnd.microsoft.icon', 'href' => $this->basePath() . '/img/favicon.ico'))
                        ->prependStylesheet($this->basePath() . '/css/style.css')
                        ->prependStylesheet($this->basePath() . '/css/bootstrap-theme.min.css')
                        ->prependStylesheet($this->basePath() . '/css/bootstrap.min.css') ?>

        <!-- Scripts -->
        <?php echo $this->headScript()
            ->prependFile($this->basePath() . '/js/bootstrap.min.js')
            ->prependFile($this->basePath() . '/js/jquery.min.js')
            ->prependFile($this->basePath() . '/js/respond.min.js', 'text/javascript', array('conditional' => 'lt IE 9',))
            ->prependFile($this->basePath() . '/js/html5shiv.js',   'text/javascript', array('conditional' => 'lt IE 9',))
        ; ?>

        <!-- view image -->
        <link rel="stylesheet" href="//netdna.bootstrapcdn.com/bootstrap/3.0.0/css/bootstrap.min.css">
		<link rel="stylesheet" href="//blueimp.github.io/Gallery/css/blueimp-gallery.min.css">
		<link rel="stylesheet" href="<?php echo $this->basePath();?>/css/bootstrap-image-gallery.min.css">

</head>
<body style="margin-top:-60px; background-color:#E6F0A4;">
	
	<!-- view image -->
	<!-- The Bootstrap Image Gallery lightbox, should be a child element of the document body -->
	<div id="blueimp-gallery" class="blueimp-gallery">
	    <!-- The container for the modal slides -->
	    <div class="slides"></div>
	    <!-- Controls for the borderless lightbox -->
	    <h3 class="title"></h3>
	    <a class="prev">‹</a>
	    <a class="next">›</a>
	    <a class="close">×</a>
	    <a class="play-pause"></a>
	    <ol class="indicator"></ol>
	    <!-- The modal dialog, which will be used to wrap the lightbox content -->
	    <div class="modal fade">
	        <div class="modal-dialog">
	            <div class="modal-content">
	                <div class="modal-header">
	                    <button type="button" class="close" aria-hidden="true">&times;</button>
	                    <h4 class="modal-title"></h4>
	                </div>
	                <div class="modal-body next"></div>
	                <div class="modal-footer">
	                    <button type="button" class="btn btn-default pull-left prev">
	                        <i class="glyphicon glyphicon-chevron-left"></i>
	                        Previous
	                    </button>
	                    <button type="button" class="btn btn-primary next">
	                        Next
	                        <i class="glyphicon glyphicon-chevron-right"></i>
	                    </button>
	                </div>
	            </div>
	        </div>
	    </div>
	</div>




	<div id="header">	
	<?php	
		$url = $this->url('rao_vat/crud', array(
		     'action' => 'login'
		 ));
	?>	 
	<form method="post" action="<?php echo $url; ?>">	
		<table border="0" align="right" style="margin-top:50px;margin-right:0px">
		<?php
		if ($this->zfcUserIdentity()) 
		{?>
			<tr>
				
				<td>
					<button type="submit" class="btn btn-primary" disabled="disabled"><?php echo "Chào: ".$this->zfcUserIdentity()->getEmail();?></button>								
				</td>
				<td>	
					<a href="<?php echo $this->url('rao_vat/crud',array('action'=>'logout'));?>">
         				<button type="button" class="btn btn-primary">
        					Thoát
     					</button>
     				</a>
				</td>
			</tr>
			<tr>
				<td colspan="2">
					<a href="<?php echo $this->url('rao_vat/crud', array('action'=>'add')); ?>" style="text-decoration: none;" title="Đăng tin miễn phí. Đăng nhập để đăng tin Vip">
						<button type="button" class="btn btn-warning"  name="btDangTin" style="width:100%;">Đăng tin miễn phí</button>
					</a>
				</td>
			</tr>
		<?php
		}
		else
		{?>
			<tr>
				<td>
					<button type="submit" class="btn btn-primary" style="width:100%;">
						Đăng nhập
					</button>
					</br>&nbsp;
				</td>
				<td style="text-align:right">					
				  <div class="form-group">
				    <input type="email" class="form-control" id="exampleInputEmail1" name="identity" placeholder="Enter email">
				  </div>
				</td>
				<td>
					<div class="form-group">
				    <input type="password" class="form-control" id="exampleInputPassword1" name="credential" placeholder="Password">
				  </div>
					
				</td>
			</tr>
			<tr>
				<td>
					<a href="<?php echo $this->url('rao_vat/crud', array('action'=>'add'));?>" style="text-decoration: none;" title="Đăng tin miễn phí. Đăng nhập để đăng tin Vip">
						<button type="button" class="btn btn-warning"  name="btDangTin" style="width:100%;">Đăng tin miễn phí</button>
					</a>
					
				</td>
				<td align="center">
					<a href="<?php echo $this->url('zfcuser/register', array('action'=>'register'));?>" title="Đăng ký để đăng tin Vip">
						<button type="button" class="btn btn-primary" style="width:100%;">
							Đăng ký
						</button>
					</a>
				</td>
				<td align="center">
					<a href="#" onclick="return tb();">
						<button type="button" class="btn btn-primary" style="width:100%;">
							Quên mật khẩu
						</button>
					</a>
				</td>
			</tr>
		<?php
		}
		?>
			
		</table>
	</form>
		<div class="section">
			<div class="logo">
				<a href="<?php echo $this->url('rao_vat'); ?>">
				</a>
			</div>				
		</div>
		
	</div>
	<div id="body">
		<?php	
			$url = $this->url('rao_vat/crud', array(
			     'action' => 'timKiem'
			 ));
		?>

		<form name="frm_tiemkiem" method="post" action="<?php echo $url; ?>">
			<table border="0">
				<tr>
					<!-- <td>Tiêu đề</td> -->
					<td style="width:300px;">						
						<input type="text" name="tk_theo_tieu_de" class="form-control" placeholder="Tiêu đề bảng tin" title="Tìm theo tiêu đề bảng tin">
					</td>

					<td>&nbsp;</td>
					<td style="width:90px;">						
						<input type="number" name="tk_theo_gia_tu" class="form-control" min="100" step="100" placeholder="Giá từ" title="Giá phải là số">
					</td>
					<td> 
						<i style="font-size:20px">-</i>
					</td>
					<td style="width:90px;">						
						<input type="number" name="tk_theo_gia_den" class="form-control" min="100" step="100" placeholder="Đến" title="Giá phải là số">
					</td>

					<td>&nbsp;</td>
					<td style="width:220px;">		
					<?php $danhMucs=$this->ChangeArrayFromObjectTermTaxonomy('danh-muc'); ?>		
						<select class="form-control" name="tk_theo_id_danh_muc">
							<option value="">&nbsp;---Tìm theo danh mục---</option>
						<?php foreach($danhMucs as $idDM=>$danhMuc){ ?>
						  	<option value="<?php echo $idDM; ?>"><?php echo $danhMuc;?></option>	  
						<?php } ?>
						</select>					
					</td>

					<td>&nbsp;</td>
					<td style="width:220px;">
						<?php $khuVucs=$this->ChangeArrayFromObjectTermTaxonomy('khu-vuc'); ?>	
						<select class="form-control" name="tk_theo_id_khu_vuc">
							<option value="">&nbsp;---Tìm theo khu vực---</option>
							<?php foreach($khuVucs as $idKV=>$khuVuc){ ?>
						  	<option value="<?php echo $idKV; ?>"><?php echo $khuVuc; ?></option>
						  	<?php } ?>						  
						</select>					
					</td>

					<td>
						<button type="submit" class="btn btn-primary">Tìm</button>
					</td>
				</tr>
			</table>
		</form>
		<?php echo $this->content; ?>
	</div>
	<div id="footer">
		<div>
			<div class="connect">
				<a href="http://freewebsitetemplates.com/go/twitter/" id="twitter">twitter</a>
				<a href="http://freewebsitetemplates.com/go/facebook/" id="facebook">facebook</a>
				<a href="http://freewebsitetemplates.com/go/googleplus/" id="googleplus">googleplus</a>
				<a href="http://pinterest.com/fwtemplates/" id="pinterest">pinterest</a>
			</div>
			<p>
				&copy; Copyright 2014 | S3U Group.
			</p>
		</div>
	</div>
	<!-- view image -->
	<script src="//ajax.googleapis.com/ajax/libs/jquery/1.11.1/jquery.min.js"></script>
	<script src="//blueimp.github.io/Gallery/js/jquery.blueimp-gallery.min.js"></script>
	<script src="<?php echo $this->basePath();?>/js/bootstrap-image-gallery.min.js"></script>
</body>
</html>