<!DOCTYPE HTML>
<!-- Website Template by freewebsitetemplates.com -->
<html>
<head>
	<meta charset="UTF-8">
	<title>Rao vặt</title>
	<link rel="stylesheet" href="<?php echo $this->basePath();?>/css/style-template.css" type="text/css">
</head>
<body>
	<div id="header">
		<div class="section">
			<div class="logo">
				<a href="index.html">Raovat.vn</a>
			</div>
			<!-- <ul>
				<li class="selected">
					<a href="index.html">home</a>
				</li>
				<li>
					<a href="about.html">about</a>
				</li>
				<li>
					<a href="hairstyle.html">hairstyles</a>
				</li>
				<li>
					<a href="news.html">news</a>
				</li>
				<li>
					<a href="contact.html">contact</a>
				</li>
			</ul> -->
		</div>
		<!-- <div class="article">
			<img src="<?php echo $this->basePath();?>/images/great-hairstyle.jpg" alt="">
			<h1>Great hairstyle comes from the experts.</h1>
		</div> -->
	</div>
	<div id="body">
		<?php echo $this->content; ?>
	</div>
	<div id="footer">
		<div>
			<div class="connect">
				<a href="http://freewebsitetemplates.com/go/twitter/" id="twitter">twitter</a>
				<a href="http://freewebsitetemplates.com/go/facebook/" id="facebook">facebook</a>
				<a href="http://freewebsitetemplates.com/go/googleplus/" id="googleplus">googleplus</a>
				<a href="http://pinterest.com/fwtemplates/" id="pinterest">pinterest</a>
			</div>
			<p>
				&copy; Copyright 2014 | S3U Group.
			</p>
		</div>
	</div>
</body>
</html>